kind: pipeline
type: docker
name: sync-tifinity-io

clone:
  disable: true

steps:
# - name: ssh
#   image: alpine
#   environment:
#     SSH_KEY:
#       from_secret: SSH_KEY
#   commands:
#     - apk add openssh
#     - apk add git
#     - mkdir $HOME/.ssh
#     - echo -e "$SSH_KEY" > $HOME/.ssh/id_rsa
#     - chmod 600 $HOME/.ssh/id_rsa
#     - touch $HOME/.ssh/known_hosts
#     - chmod 600 $HOME/.ssh/known_hosts
#     - ssh-keyscan -H github.com > $HOME/.ssh/known_hosts
#     - cat $HOME/.ssh/id_rsa
#     - git clone --recursive git@github.com:Tifinity/Tifinity-Blog.git

- name: clone
  image: centos
  environment:
    SSH_KEY:
      from_secret: GIT_SSH_DIRECT
  commands:
    - yum install -y git
    - yum install -y openssh-clients
    - mkdir $HOME/.ssh
    - echo -e "$SSH_KEY" > $HOME/.ssh/id_rsa
    - chmod 600 $HOME/.ssh/id_rsa
    - touch $HOME/.ssh/known_hosts
    - chmod 600 $HOME/.ssh/known_hosts
    - ssh-keyscan -H github.com > $HOME/.ssh/known_hosts
    - git clone --recursive git@github.com:Tifinity/HelloGo.git
  when:
    branch:
    - master

# - name: clone
#   image: plugins/git-action:1
#   settings:
#     actions:
#       - clone
#     remote: git@github.com:Tifinity/Tifinity-Blog.git
#     branch: master
#     path: /drone/src
#     ssh_key:
#       form_secret: GIT_PUSH_SSH_KEY

trigger:
  event:
  - push