kind: pipeline
type: docker
name: sync-tifinity-io

clone:
  disable: true

steps:
- name: clone
  image: centos
  environment:
    SSH_KEY:
      from_secret: GIT_SSH_DIRECT
  commands:
    - yum install -y git
    - yum install -y openssh-clients
    - mkdir $HOME/.ssh
    - echo "$SSH_KEY" > $HOME/.ssh/id_rsa
    - chmod 600 $HOME/.ssh/id_rsa
    - touch $HOME/.ssh/known_hosts
    - chmod 600 $HOME/.ssh/known_hosts
    - ssh-keyscan -H github.com > $HOME/.ssh/known_hosts
    - mkdir clone
    - git clone --recursive git@github.com:Tifinity/HelloGo.git clone
  when:
    branch:
      - master

- name: clone2
  image: centos
  environment:
    SSH_KEY:
      from_secret: GIT_SSH_SINGLEWITHN
  commands:
    - yum install -y git
    - yum install -y openssh-clients
    - mkdir $HOME/.ssh
    - echo "$SSH_KEY" > $HOME/.ssh/id_rsa
    - chmod 600 $HOME/.ssh/id_rsa
    - touch $HOME/.ssh/known_hosts
    - chmod 600 $HOME/.ssh/known_hosts
    - ssh-keyscan -H github.com > $HOME/.ssh/known_hosts
    - mkdir clone2
    - git clone --recursive git@github.com:Tifinity/HelloGo.git clone2
  when:
    branch:
      - master

- name: test
  image: alpine
  commands:
    - echo hello
  depends_on:
    - clone
    - clone2

# - name: clone
#   image: plugins/git-action:1
#   settings:
#     actions:
#       - clone
#     remote: git@github.com:Tifinity/Tifinity-Blog.git
#     branch: master
#     path: /drone/src
#     ssh_key:
#       form_secret: GIT_PUSH_SSH_KEY

trigger:
  event:
  - push